spring:
  profiles:
    active:
      - local
    include:
      - db
    group:
      local:
        - db-local
      dev:
        - db-dev
      prod:
        - db-prod

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true